export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_COURSE_SERVER_RESPONSE_SUCCESS =
  "CREATE_COURSE_SERVER_RESPONSE_SUCCESS";
export const CREATE_COURSE_SERVER_RESPONSE_ERROR =
  "CREATE_COURSE_SERVER_RESPONSE_ERROR";

export const GET_COURSE = "GET_COURSE";
export const GET_COURSE_DETAILS_SERVER_RESPONSE_SUCCESS =
  "GET_COURSE_DETAILS_SERVER_RESPONSE_SUCCESS";
export const GET_COURSE_DETAILS_SERVER_RESPONSE_ERROR =
  "GET_COURSE_DETAILS_SERVER_RESPONSE_ERROR";

export const GET_COURSE_BY_SEARCH = "GET_COURSE_BY_SEARCH";
export const GET_COURSE_BY_SEARCH_SERVER_RESPONSE_SUCCESS =
  "GET_COURSE_BY_SEARCH_SERVER_RESPONSE_SUCCESS";
export const GET_COURSE_BY_SEARCH_SERVER_RESPONSE_ERROR =
  "GET_COURSE_BY_SEARCH_SERVER_RESPONSE_ERROR";

export const GET_FILTER_DATA = "GET_FILTER_DATA";
export const GET_FILTER_DATA_SERVER_RESPONSE_SUCCESS =
  "GET_FILTER_DATA_SERVER_RESPONSE_SUCCESS";
export const GET_FILTER_DATA_SERVER_RESPONSE_ERROR =
  "GET_FILTER_DATA_SERVER_RESPONSE_ERROR";
